### ISSUE TITLE
Why does an error occur after installation is completed and executed?

### ISSUE THREAD

**Issue by lhj5426** [VoxelCubes/PanelCleaner#119]
![image](https://github.com/user-attachments/assets/e3932ca2-b2d7-43ce-a7d8-f3d57acca0ad)

2024-11-12 14:30:04.237 | INFO     | pcleaner.gui.launcher:launch:93 - 
- Program Information -
Program: Panel Cleaner 2.10.0
Executing from: C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\gui\launcher.py
Log file: F:\Users\<username>\AppData\Roaming\pcleaner\cache\pcleaner.log
Config file: F:\Users\<username>\AppData\Roaming\pcleaner\pcleanerconfig.ini
Cache directory: F:\Users\<username>\AppData\Roaming\pcleaner\cache
- System Information -
Operating System: Windows 10
Python Version: 3.10.0 | packaged by conda-forge | (default, Nov 10 2021, 13:20:59) [MSC v.1916 64 bit (AMD64)]
PySide (Qt) Version: 6.8.0.2
Available Qt Themes: windows11, windowsvista, Windows, Fusion
Current Qt Theme: System Default
Current Icon Theme: System Default
System locale: zh_CN
Architecture: AMD64
CPU Cores: 4
Memory: 15.96 GiB
Swap: 13.00 GiB
GPU: NVIDIA GeForce GTX 970 (CUDA enabled)
    CUDA Version: 11.8
    CUDA Cores: 13
    VRAM: 4.00 GiB

2024-11-12 14:30:05.632 | INFO     | pcleaner.gui.launcher:launch:110 - Using locale zh_CN.
2024-11-12 14:30:05.638 | DEBUG    | pcleaner.gui.launcher:launch:117 - Loaded built-in Qt translations for zh_CN.
2024-11-12 14:30:05.653 | DEBUG    | pcleaner.gui.launcher:launch:125 - Loaded built-in Qt base translations for zh_CN.
2024-11-12 14:30:22.086 | DEBUG    | pcleaner.gui.mainwindow_driver:ensure_models_downloaded:453 - Text detector model already downloaded.
2024-11-12 14:30:22.113 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_ui:278 - Purging missing profiles.
2024-11-12 14:30:22.117 | INFO     | pcleaner.gui.mainwindow_driver:initialize_profiles:1042 - Found profiles: [('Default', None), ('1111', WindowsPath('F:/Users/<username>/AppData/Roaming/pcleaner/profiles/1111.conf'))]
2024-11-12 14:30:22.130 | DEBUG    | pcleaner.config:load_profile:1238 - Loading profile None...
2024-11-12 14:30:22.132 | DEBUG    | pcleaner.config:load_profile:1245 - Loading builtin default profile
2024-11-12 14:30:22.412 | DEBUG    | pcleaner.gui.mainwindow_driver:load_current_profile:1206 - Loading current profile.
2024-11-12 14:30:22.414 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:502 - Setting profile values
2024-11-12 14:30:22.421 | DEBUG    | pcleaner.gui.mainwindow_driver:apply_profile:1338 - Applying profile.
2024-11-12 14:30:22.572 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:797 - Loading included font from C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\data\NotoMono-Regular.ttf
2024-11-12 14:30:22.575 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:800 - Loaded included font
2024-11-12 14:30:22.594 | DEBUG    | pcleaner.gui.mainwindow_driver:save_default_palette:167 - Placeholder color: #000000
2024-11-12 14:30:22.596 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:171 - Default Qt Style: windowsvista
2024-11-12 14:30:22.599 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:172 - Default Icon Theme: breeze
2024-11-12 14:30:22.601 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:188 - Using system theme.
2024-11-12 14:30:22.603 | INFO     | pcleaner.gui.mainwindow_driver:changeEvent:259 - Theme is dark: False
2024-11-12 14:30:22.613 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:236 - Theme is dark: False
2024-11-12 14:30:22.969 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:525 - Char width: 6, columns: 74, required width: 444
2024-11-12 14:30:22.985 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:556 - Splitter sizes: [375, 1000, 463]
2024-11-12 14:30:23.013 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for Mainwindow
2024-11-12 14:30:23.015 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:685 - Worker Thread cleaning cache
2024-11-12 14:30:23.017 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:692 - Worker Thread loading OCR model.
2024-11-12 14:30:23.019 | INFO     | pcleaner.gui.mainwindow_driver:clean_cache:782 - Cleaning image cache.
2024-11-12 14:30:23.023 | INFO     | pcleaner.ocr.ocr_mangaocr:__new__:17 - Creating the MangaOcr instance
2024-11-12 14:30:23.034 | INFO     | manga_ocr.ocr:__init__:16 - Loading OCR model from kha-white/manga-ocr-base
2024-11-12 14:30:31.751 | INFO     | manga_ocr.ocr:__init__:22 - Using CUDA
2024-11-12 14:30:33.416 | INFO     | manga_ocr.ocr:__init__:35 - OCR ready
2024-11-12 14:30:33.421 | INFO     | pcleaner.gui.mainwindow_driver:load_ocr_model:708 - Loaded OCR model (10.40s)
2024-11-12 14:31:05.708 | DEBUG    | pcleaner.gui.file_table:handleDrop:212 - Dropped J:/G/Desktop/OCR替换测试/剪贴板图片 (2).png
2024-11-12 14:31:05.715 | DEBUG    | pcleaner.gui.file_table:add_file:264 - Requesting to add "J:\G\Desktop\OCR替换测试\剪贴板图片 (2).png"
2024-11-12 14:31:05.726 | DEBUG    | pcleaner.gui.file_table:repopulate_table:330 - Repopulating table
2024-11-12 14:31:05.749 | INFO     | pcleaner.gui.file_table:lazy_load_images:648 - Dispatching image loading workers
2024-11-12 14:31:05.760 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:654 - Worker Thread loading image J:\G\Desktop\OCR替换测试\剪贴板图片 (2).png
2024-11-12 14:31:39.433 | DEBUG    | pcleaner.gui.image_details_driver:__init__:130 - Opening details tab for J:\G\Desktop\OCR替换测试\剪贴板图片 (2).png
2024-11-12 14:31:39.528 | DEBUG    | pcleaner.gui.image_details_driver:init_sidebar:363 - Setting scroll area width to 411
2024-11-12 14:31:39.558 | INFO     | pcleaner.gui.processing:generate_output:173 - Running text detection AI model for 1 images...
2024-11-12 14:31:40.899 | INFO     | pcleaner.gui.processing:generate_output:562 - Finished processing 1 images.
2024-11-12 14:31:40.920 | INFO     | pcleaner.gui.image_details_driver:output_worker_result:652 - Output worker finished.
2024-11-12 14:35:13.720 | INFO     | pcleaner.gui.processing:generate_output:173 - Running text detection AI model for 1 images...
2024-11-12 14:35:15.280 | CRITICAL | pcleaner.gui.image_details_driver:output_worker_error:656 - Output generation failed:
Traceback (most recent call last):

> File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {'progress_callback': <PySide6.QtCore.SignalInstance progress(PyObject) at 0x000001CA73D69790>, 'abort_flag': <pcleaner.gui.w...
             │    │   │    │       └ <pcleaner.gui.worker_thread.Worker object at 0x000001CAEBD275C0>
             │    │   │    └ (<Output.ai_mask: 2>,)
             │    │   └ <pcleaner.gui.worker_thread.Worker object at 0x000001CAEBD275C0>
             │    └ <bound method ImageDetailsWidget.generate_output of <pcleaner.gui.image_details_driver.ImageDetailsWidget(0x1cad21f4fd0, name...
             └ <pcleaner.gui.worker_thread.Worker object at 0x000001CAEBD275C0>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\gui\image_details_driver.py", line 640, in generate_output
    prc.generate_output(
    │   └ <function generate_output at 0x000001CA63BC70A0>
    └ <module 'pcleaner.gui.processing' from 'C:\\Users\\<username>\\.conda\\envs\\pcleaner\\lib\\site-packages\\pcleaner\\gui\\process...

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\gui\processing.py", line 180, in generate_output
    ctm.model2annotations_gui(
    │   └ <function model2annotations_gui at 0x000001CA63BC7D00>
    └ <module 'pcleaner.gui.ctd_interface_gui' from 'C:\\Users\\<username>\\.conda\\envs\\pcleaner\\lib\\site-packages\\pcleaner\\gui\\...

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\gui\ctd_interface_gui.py", line 124, in model2annotations_gui
    process_image(
    └ <function process_image at 0x000001CA63ABC9D0>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\ctd_interface.py", line 161, in process_image
    mask, mask_refined, blk_list = model(
                                   └ <pcleaner.comic_text_detector.inference.TextDetector object at 0x000001CA73D23EB0>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           │     │       └ {'refine_mode': 1, 'keep_undetected_mask': True}
           │     └ (<pcleaner.comic_text_detector.inference.TextDetector object at 0x000001CA73D23EB0>, array([[[255, 255, 255],
           │               [255, 2...
           └ <function TextDetector.__call__ at 0x000001CA63A9FF40>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\comic_text_detector\inference.py", line 179, in __call__
    blks = postprocess_yolo(blks, self.conf_thresh, self.nms_thresh, resize_ratio)
           │                │     │    │            │    │           └ (0.43359375, 0.4337585868498528)
           │                │     │    │            │    └ 0.35
           │                │     │    │            └ <pcleaner.comic_text_detector.inference.TextDetector object at 0x000001CA73D23EB0>
           │                │     │    └ 0.4
           │                │     └ <pcleaner.comic_text_detector.inference.TextDetector object at 0x000001CA73D23EB0>
           │                └ tensor([[[6.3744e+00, 6.9215e+00, 1.5298e+01,  ..., 6.9996e-06,
           │                            9.2340e-02, 9.0304e-01],
           │                           [1.2604e+01, 7.16...
           └ <function postprocess_yolo at 0x000001CA63A9FD90>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\comic_text_detector\inference.py", line 115, in postprocess_yolo
    det = non_max_suppression(det, conf_thresh, nms_thresh)[0]
          │                   │    │            └ 0.35
          │                   │    └ 0.4
          │                   └ tensor([[[6.3744e+00, 6.9215e+00, 1.5298e+01,  ..., 6.9996e-06,
          │                               9.2340e-02, 9.0304e-01],
          │                              [1.2604e+01, 7.16...
          └ <function non_max_suppression at 0x000001CA639152D0>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\pcleaner\comic_text_detector\utils\yolov5_utils.py", line 263, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)  # NMS
        │           │   │   │      │       └ 0.35
        │           │   │   │      └ tensor([0.8788, 0.8685, 0.8797, 0.8700, 0.9214, 0.4724, 0.9533, 0.5235, 0.9003,
        │           │   │   │                0.5234, 0.8687, 0.8950, 0.8925, 0.850...
        │           │   │   └ tensor([[4235.6978, 4453.9883, 4260.4624, 4530.3599],
        │           │   │             [4236.2734, 4454.1646, 4260.3223, 4530.3940],
        │           │   │             [4235.854...
        │           │   └ <function nms at 0x000001CA5471EA70>
        │           └ <module 'torchvision.ops' from 'C:\\Users\\<username>\\.conda\\envs\\pcleaner\\lib\\site-packages\\torchvision\\ops\\__init__.py'>
        └ <module 'torchvision' from 'C:\\Users\\<username>\\.conda\\envs\\pcleaner\\lib\\site-packages\\torchvision\\__init__.py'>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\torchvision\ops\boxes.py", line 41, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           │     │   │           │   │      │       └ 0.35
           │     │   │           │   │      └ tensor([0.8788, 0.8685, 0.8797, 0.8700, 0.9214, 0.4724, 0.9533, 0.5235, 0.9003,
           │     │   │           │   │                0.5234, 0.8687, 0.8950, 0.8925, 0.850...
           │     │   │           │   └ tensor([[4235.6978, 4453.9883, 4260.4624, 4530.3599],
           │     │   │           │             [4236.2734, 4454.1646, 4260.3223, 4530.3940],
           │     │   │           │             [4235.854...
           │     │   │           └ <OpOverloadPacket(op='torchvision.nms')>
           │     │   └ <module 'torch.ops.torchvision' from 'torch.ops'>
           │     └ <module 'torch.ops' from '_ops.py'>
           └ <module 'torch' from 'C:\\Users\\<username>\\.conda\\envs\\pcleaner\\lib\\site-packages\\torch\\__init__.py'>

  File "C:\Users\<username>\.conda\envs\pcleaner\lib\site-packages\torch\_ops.py", line 1116, in __call__
    return self._op(*args, **(kwargs or {}))
           │    │    │        └ {}
           │    │    └ (tensor([[4235.6978, 4453.9883, 4260.4624, 4530.3599],
           │    │              [4236.2734, 4454.1646, 4260.3223, 4530.3940],
           │    │              [4235.85...
           │    └ <built-in method nms of PyCapsule object at 0x000001CA6C884ED0>
           └ <OpOverloadPacket(op='torchvision.nms')>

NotImplementedError: Could not run 'torchvision::nms' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'torchvision::nms' is only available for these backends: [CPU, Meta, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradMPS, AutogradXPU, AutogradHPU, AutogradLazy, AutogradMeta, Tracer, AutocastCPU, AutocastXPU, AutocastMPS, AutocastCUDA, FuncTorchBatched, BatchedNestedTensor, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PreDispatch, PythonDispatcher].

CPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\cpu\nms_kernel.cpp:112 [kernel]
Meta: registered at /dev/null:184 [kernel]
QuantizedCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\quantized\cpu\qnms_kernel.cpp:124 [kernel]
BackendSelect: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:153 [backend fallback]
FuncTorchDynamicLayerBackMode: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\DynamicLayer.cpp:497 [backend fallback]
Functionalize: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\FunctionalizeFallbackKernel.cpp:349 [backend fallback]
Named: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\ConjugateFallback.cpp:17 [backend fallback]
Negative: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\NegateFallback.cpp:18 [backend fallback]
ZeroTensor: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\ZeroTensorFallback.cpp:86 [backend fallback]
ADInplaceOrView: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:96 [backend fallback]
AutogradOther: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:63 [backend fallback]
AutogradCPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:67 [backend fallback]
AutogradCUDA: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:75 [backend fallback]
AutogradXLA: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:79 [backend fallback]
AutogradMPS: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:87 [backend fallback]
AutogradXPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:71 [backend fallback]
AutogradHPU: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:100 [backend fallback]
AutogradLazy: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:83 [backend fallback]
AutogradMeta: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\VariableFallbackKernel.cpp:91 [backend fallback]
Tracer: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\autograd\TraceTypeManual.cpp:294 [backend fallback]
AutocastCPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:34 [kernel]
AutocastXPU: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:41 [kernel]
AutocastMPS: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\autocast_mode.cpp:209 [backend fallback]
AutocastCUDA: registered at C:\actions-runner\_work\vision\vision\pytorch\vision\torchvision\csrc\ops\autocast\nms_kernel.cpp:27 [kernel]
FuncTorchBatched: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:731 [backend fallback]
BatchedNestedTensor: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\LegacyBatchingRegistrations.cpp:758 [backend fallback]
FuncTorchVmapMode: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\VmapModeRegistrations.cpp:27 [backend fallback]
Batched: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\LegacyBatchingRegistrations.cpp:1075 [backend fallback]
VmapMode: fallthrough registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\VmapModeRegistrations.cpp:33 [backend fallback]
FuncTorchGradWrapper: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\TensorWrapper.cpp:207 [backend fallback]
PythonTLSSnapshot: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:161 [backend fallback]
FuncTorchDynamicLayerFrontMode: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\functorch\DynamicLayer.cpp:493 [backend fallback]
PreDispatch: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:165 [backend fallback]
PythonDispatcher: registered at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\core\PythonFallbackKernel.cpp:157 [backend fallback]

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/6fe98bba-eacf-495b-ab62-0f19993970fc)
No matter which step I execute, an error occurs, and it can't run properly at all. What could be the reason?

Create Python environment:


conda create -n pcleaner python==3.10
List environments:

bash
复制代码
conda env list
Activate environment:


conda activate pcleaner
Install packages:


pip install pcleaner
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
These are my installation steps. Did I make any mistakes?

**Comment by lhj5426** [comment]
I am running this on Windows 10.

**Comment by lhj5426** [comment]
The direct download of the pre-packaged EXE runs correctly, but I'm wondering if I made any mistakes during the installation. Although the EXE works, not being able to use the GUI is quite disappointing.
![image](https://github.com/user-attachments/assets/d4b7d436-3afe-4faa-918a-aa512096346d)

**Comment by VoxelCubes** [comment]
This is the same issue as in https://github.com/VoxelCubes/PanelCleaner/issues/117. Your GPU is too old and weak to be used for this AI model. You can still run the python package natively by installing the CPU-only packages (which are the default on windows anyway, but maybe anaconda did something right here and tried to help you out (to your detriment)) https://pytorch.org/get-started/locally/

This way you can use the CLI, if that's what you actually meant with
> Although the EXE works, not being able to use the GUI is quite disappointing.

It's unfortunate but you will have to stick with CPU-processing. At least the output is identical, GPU just does it faster.

**Comment by VoxelCubes** [comment]
Your installation steps should indeed have worked, though note that you don't need to use python 3.10. Newer versions of python work too and are a bit faster.

Thank you very much for including the debug log, that helped a lot!

**Comment by lhj5426** [comment]
> Your installation steps should indeed have worked, though note that you don't need to use python 3.10. Newer versions of python work too and are a bit faster.
> 
> Thank you very much for including the debug log, that helped a lot!
Does this software consume more GPU resources compared to this open-source software? I’ve been able to run this software on the host that gave this error without any issues. Also, I’ve trained and inferred comics using YOLOv11 myself without any problems. Could it be that this software requires more computational power?
https://github.com/dmMaze/BallonsTranslator

**Comment by VoxelCubes** [comment]
I don't know, it uses the same model as the one you linked, but the error occurs in the part of the code from that very project, not something I wrote, so unfortunately I can't really say.

The error says that a cuda function isn't available in your torch installation, so either the gpu doesn't support it or you ended up with the wrong version of cuda, somehow.
A gtx970 should support cuda versions up to 11, so it seems like you got a supported version? Maybe try an older one? I'm sorry, I can't find a solution to this.

**Comment by lhj5426** [comment]
> I don't know, it uses the same model as the one you linked, but the error occurs in the part of the code from that very project (the comic text detector module), not something I wrote, so unfortunately I can't really say.
> 
> The error says that a cuda function isn't available in your torch installation, so either the gpu doesn't support it or you ended up with the wrong version of cuda, somehow. A gtx970 should support cuda versions up to 11, so it seems like you got a supported version? Maybe try an older one? It's very odd. I'm sorry, I can't find a solution to this.
![image](https://github.com/user-attachments/assets/fe30cca8-94f3-4219-9f74-5267761e69ce)

After several attempts and error messages, the issue has been resolved.

![image](https://github.com/user-attachments/assets/f826a85f-d9a3-4077-a1aa-c2878be59fd9)

The solution was to uninstall by running `pip uninstall torch torchvision`, then reinstall with `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`. After that, running `pcleaner-gui` allows CUDA to be used.

**Comment by lhj5426** [comment]
1.conda create -n pcle  python==3.12

2.conda env list

3.conda activate pcle

4.pip install pcleaner
5.pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
6.pip uninstall torch torchvision
7.pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
8.pcleaner-gui

**Comment by lhj5426** [comment]
![image](https://github.com/user-attachments/assets/da04b358-925f-4c69-97e2-db0ed89682e1)
The overall result is pretty good.

**Comment by VoxelCubes** [comment]
That's odd, you used the same cuda version 11.8 but it works now? I see you opted for a newer python version, I wonder if that was the fix here?

Either way I'm very glad you got it working, happy cleaning!

**Comment by lhj5426** [comment]
> That's odd, you used the same cuda version 11.8 but it works now? I see you opted for a newer python version, I wonder if that was the fix here?
> 
> Either way I'm very glad you got it working, happy cleaning!

I'm not sure either. I just asked AI, and whatever AI told me, I copied and pasted, and miraculously it worked. This is the screenshot of my conversation with AI.
![image](https://github.com/user-attachments/assets/66316841-388f-47eb-be77-4af88cc9bc5a)
![image](https://github.com/user-attachments/assets/0389f95f-b381-430d-8e9a-de105977208d)

**Comment by VoxelCubes** [comment]
Well, whatever it was, I'm happy you have cuda acceleration.
