### ISSUE TITLE
MergedImageFile bug

### ISSUE THREAD

**Issue by wolfkingal2000** [VoxelCubes/PanelCleaner#128]
I fix Cuba problem thank you bug give this error  when   outputing

2024-12-03 01:52:34.219 | INFO     | pcleaner.gui.launcher:launch:93 - 
- Program Information -
Program: Panel Cleaner 2.11.0
Executing from: C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\launcher.py
Log file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\pcleaner.log
Config file: C:\Users\aaa13\AppData\Roaming\pcleaner\pcleanerconfig.ini
Cache directory: C:\Users\aaa13\AppData\Roaming\pcleaner\cache
- System Information -
Operating System: Windows 10
Python Version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
PySide (Qt) Version: 6.7.2
Available Qt Themes: windows11, windowsvista, Windows, Fusion
Current Qt Theme: System Default
Current Icon Theme: System Default
System locale: en_US
Architecture: AMD64
CPU Cores: 4
Memory: 15.90 GiB
Swap: 47.76 GiB
GPU: NVIDIA GeForce 840M (CUDA enabled)
    CUDA Version: 12.1
    CUDA Cores: 3
    VRAM: 4.00 GiB

2024-12-03 01:52:39.139 | INFO     | pcleaner.gui.launcher:launch:110 - Using locale en_US.
2024-12-03 01:52:44.946 | DEBUG    | pcleaner.gui.launcher:launch:117 - Loaded built-in Qt translations for en_US.
2024-12-03 01:52:45.012 | DEBUG    | pcleaner.gui.launcher:launch:125 - Loaded built-in Qt base translations for en_US.
2024-12-03 01:55:48.229 | DEBUG    | pcleaner.gui.mainwindow_driver:ensure_models_downloaded:480 - Text detector model already downloaded.
2024-12-03 01:55:48.580 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_ui:290 - Purging missing profiles.
2024-12-03 01:55:48.593 | INFO     | pcleaner.gui.mainwindow_driver:initialize_profiles:1240 - Found profiles: [('Default', None), ('kingal', WindowsPath('C:/Users/aaa13/AppData/Roaming/pcleaner/profiles/kingal.conf')), ('god', WindowsPath('C:/Users/aaa13/AppData/Roaming/pcleaner/profiles/god.conf'))]
2024-12-03 01:55:48.768 | DEBUG    | pcleaner.config:load_profile:1361 - Loading profile None...
2024-12-03 01:55:48.768 | DEBUG    | pcleaner.config:load_profile:1368 - Loading builtin default profile
2024-12-03 01:55:49.325 | DEBUG    | pcleaner.gui.mainwindow_driver:load_current_profile:1400 - Loading current profile.
2024-12-03 01:55:49.326 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:546 - Setting profile values
2024-12-03 01:55:49.375 | DEBUG    | pcleaner.gui.mainwindow_driver:apply_profile:1534 - Applying profile.
2024-12-03 01:55:49.378 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:546 - Setting profile values
2024-12-03 01:55:49.398 | ERROR    | pcleaner.ocr.ocr_tesseract:available_langs:32 - Error checking Tesseract available language data: tesseract is not installed or it's not in your PATH. See README file for more information.
2024-12-03 01:55:49.401 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:825 - Loading included font from C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\data\NotoMono-Regular.ttf
2024-12-03 01:55:49.559 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:828 - Loaded included font
2024-12-03 01:55:49.667 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 01:55:49.699 | DEBUG    | pcleaner.gui.mainwindow_driver:save_default_palette:179 - Placeholder color: #000000
2024-12-03 01:55:49.925 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:183 - Default Qt Style: windowsvista
2024-12-03 01:55:49.926 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:184 - Default Icon Theme: breeze
2024-12-03 01:55:49.926 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:207 - Using theme: breeze-dark
2024-12-03 01:55:50.872 | INFO     | pcleaner.gui.mainwindow_driver:changeEvent:271 - Theme is dark: True
2024-12-03 01:55:50.939 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 01:55:50.945 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:248 - Theme is dark: True
2024-12-03 01:55:50.981 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 01:55:54.165 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:553 - Char width: 6, columns: 74, required width: 444
2024-12-03 01:55:54.284 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:584 - Splitter sizes: [400, 669, 460]
2024-12-03 01:55:54.391 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for Mainwindow
2024-12-03 01:55:54.392 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:713 - Worker Thread cleaning cache
2024-12-03 01:55:54.392 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:720 - Worker Thread loading OCR model.
2024-12-03 01:55:54.410 | INFO     | pcleaner.ocr.ocr_mangaocr:__new__:17 - Creating the MangaOcr instance
2024-12-03 01:55:54.411 | INFO     | manga_ocr.ocr:__init__:15 - Loading OCR model from kha-white/manga-ocr-base
2024-12-03 01:55:54.412 | INFO     | pcleaner.gui.mainwindow_driver:clean_cache:810 - Cleaning image cache.
2024-12-03 01:56:42.198 | INFO     | manga_ocr.ocr:__init__:25 - Using CUDA
2024-12-03 01:57:02.955 | INFO     | manga_ocr.ocr:__init__:38 - OCR ready
2024-12-03 01:57:02.956 | INFO     | pcleaner.gui.mainwindow_driver:load_ocr_model:736 - Loaded OCR model (68.55s)
2024-12-03 02:05:27.405 | DEBUG    | pcleaner.gui.file_table:handleDrop:219 - Dropped D:/edit/kuro neko/The Legendary Beasts Animal Hospital/raw/New folder (3)/Official (low quality)_Chapter 25/001.jpg
2024-12-03 02:05:27.408 | DEBUG    | pcleaner.gui.file_table:add_file:271 - Requesting to add "D:\edit\kuro neko\The Legendary Beasts Animal Hospital\raw\New folder (3)\Official (low quality)_Chapter 25\001.jpg"
2024-12-03 02:05:27.814 | DEBUG    | pcleaner.gui.file_table:repopulate_table:373 - Repopulating table
2024-12-03 02:05:27.885 | INFO     | pcleaner.gui.file_table:lazy_load_images:692 - Dispatching image loading workers
2024-12-03 02:05:27.885 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:698 - Worker Thread loading image C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_1.jpg
2024-12-03 02:05:27.886 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:698 - Worker Thread loading image C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_2.jpg
2024-12-03 02:05:27.887 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:698 - Worker Thread loading image C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_3.jpg
2024-12-03 02:05:27.887 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:698 - Worker Thread loading image C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_4.jpg
2024-12-03 02:05:27.888 | DEBUG    | pcleaner.gui.file_table:lazy_load_images:698 - Worker Thread loading image C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_5.jpg
2024-12-03 02:05:33.832 | DEBUG    | pcleaner.gui.image_details_driver:__init__:130 - Opening details tab for C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\splits_2de560293e0a41f7b1323a26b1972315\001_split_1.jpg
2024-12-03 02:05:33.938 | DEBUG    | pcleaner.gui.image_details_driver:init_sidebar:363 - Setting scroll area width to 262
2024-12-03 02:05:33.954 | INFO     | pcleaner.gui.processing:generate_output:179 - Running text detection AI model for 1 images...
2024-12-03 02:05:38.444 | INFO     | pcleaner.gui.processing:generate_output:568 - Finished processing 1 images.
2024-12-03 02:05:38.578 | DEBUG    | pcleaner.gui.image_details_driver:generate_output:636 - Output 1 is unchanged. Worker will not run.
2024-12-03 02:05:38.674 | INFO     | pcleaner.gui.image_details_driver:output_worker_result:654 - Output worker finished.
2024-12-03 02:05:38.699 | INFO     | pcleaner.gui.image_details_driver:output_worker_result:654 - Output worker finished.
2024-12-03 02:05:46.113 | DEBUG    | pcleaner.gui.image_tab:tab_close:89 - Closing tab at index 1.
2024-12-03 02:05:49.034 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 02:05:49.035 | INFO     | pcleaner.gui.mainwindow_driver:start_cleaning:1772 - Requested outputs: [<Output.denoised_output: 19>, <Output.denoise_mask: 18>]
2024-12-03 02:05:49.037 | INFO     | pcleaner.gui.processing:generate_output:179 - Running text detection AI model for 5 images...
2024-12-03 02:05:55.242 | DEBUG    | pcleaner.ctd_interface:process_image:179 - Saving json file to C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\3d95ceaf-63ed-49a0-8737-bf8e7bd97aff_001_split_1#raw.json
2024-12-03 02:05:56.532 | DEBUG    | pcleaner.ctd_interface:process_image:179 - Saving json file to C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\8e0120ff-e26c-4a62-b9b4-397125eaf948_001_split_2#raw.json
2024-12-03 02:05:57.857 | DEBUG    | pcleaner.ctd_interface:process_image:179 - Saving json file to C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\ddbafb49-b360-4359-be97-7a250c5911cd_001_split_3#raw.json
2024-12-03 02:05:59.204 | DEBUG    | pcleaner.ctd_interface:process_image:179 - Saving json file to C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\f2b35679-bfd2-4400-a9a2-707afc395ef3_001_split_4#raw.json
2024-12-03 02:06:00.575 | DEBUG    | pcleaner.ctd_interface:process_image:179 - Saving json file to C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\239d4309-7302-4792-aab4-7934f6df185a_001_split_5#raw.json
2024-12-03 02:06:00.603 | INFO     | pcleaner.gui.processing:generate_output:231 - Running preprocessing for 5 images...
2024-12-03 02:06:00.606 | DEBUG    | pcleaner.preprocessor:prep_json_file:124 - Processing json file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\3d95ceaf-63ed-49a0-8737-bf8e7bd97aff_001_split_1#raw.json
2024-12-03 02:06:00.611 | DEBUG    | pcleaner.preprocessor:prep_json_file:124 - Processing json file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\8e0120ff-e26c-4a62-b9b4-397125eaf948_001_split_2#raw.json
2024-12-03 02:06:00.616 | DEBUG    | pcleaner.preprocessor:prep_json_file:124 - Processing json file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\ddbafb49-b360-4359-be97-7a250c5911cd_001_split_3#raw.json
2024-12-03 02:06:00.620 | DEBUG    | pcleaner.preprocessor:prep_json_file:124 - Processing json file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\f2b35679-bfd2-4400-a9a2-707afc395ef3_001_split_4#raw.json
2024-12-03 02:06:00.626 | DEBUG    | pcleaner.preprocessor:prep_json_file:124 - Processing json file: C:\Users\aaa13\AppData\Roaming\pcleaner\cache\cleaner\239d4309-7302-4792-aab4-7934f6df185a_001_split_5#raw.json
2024-12-03 02:06:00.670 | INFO     | pcleaner.gui.processing:generate_output:293 - Running masker for 5 images...
2024-12-03 02:06:00.670 | INFO     | pcleaner.gui.mainwindow_driver:show_current_progress:2269 - Showing ocr analytics...
2024-12-03 02:07:05.876 | INFO     | pcleaner.gui.processing:generate_output:399 - Running denoiser for 5 images...
2024-12-03 02:07:05.877 | INFO     | pcleaner.gui.mainwindow_driver:show_current_progress:2278 - Showing masker analytics...
2024-12-03 02:07:35.836 | INFO     | pcleaner.gui.mainwindow_driver:show_current_progress:2288 - Showing denoiser analytics...
2024-12-03 02:07:35.901 | INFO     | pcleaner.gui.processing:generate_output:568 - Finished processing 5 images.
2024-12-03 02:07:35.908 | INFO     | pcleaner.gui.processing:handle_merging_splits:965 - Merging split files...
2024-12-03 02:07:40.328 | INFO     | pcleaner.gui.mainwindow_driver:output_worker_result:2107 - Output worker finished.
2024-12-03 02:07:40.329 | INFO     | pcleaner.gui.output_review_driver:__init__:86 - Opening Review Window for 5 outputs.
2024-12-03 02:07:41.066 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for output_review
2024-12-03 02:07:59.848 | DEBUG    | pcleaner.gui.mainwindow_driver:output_review_closed:2161 - Output review closed.
2024-12-03 02:08:00.917 | DEBUG    | pcleaner.gui.state_saver:save:65 - Saved state for output_review
2024-12-03 02:08:03.665 | WARNING  | pcleaner.gui.mainwindow_driver:profile_change_check:1411 - Profile change check
2024-12-03 02:08:03.666 | DEBUG    | pcleaner.config:load_profile:1361 - Loading profile 'god'...
2024-12-03 02:08:03.666 | DEBUG    | pcleaner.config:load_profile:1375 - Loading profile god from C:\Users\aaa13\AppData\Roaming\pcleaner\profiles\god.conf
2024-12-03 02:08:03.667 | INFO     | pcleaner.config:load:1007 - Loading profile C:\Users\aaa13\AppData\Roaming\pcleaner\profiles\god.conf from disk...
2024-12-03 02:08:03.678 | DEBUG    | pcleaner.gui.mainwindow_driver:load_current_profile:1400 - Loading current profile.
2024-12-03 02:08:03.678 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:546 - Setting profile values
2024-12-03 02:08:08.769 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 02:08:08.770 | INFO     | pcleaner.gui.mainwindow_driver:start_cleaning:1772 - Requested outputs: [<Output.inpainted_output: 21>, <Output.inpainted_mask: 20>]
2024-12-03 02:08:08.781 | INFO     | pcleaner.gui.processing:generate_output:495 - Running inpainting for 5 images...
2024-12-03 02:09:27.029 | INFO     | pcleaner.gui.processing:generate_output:568 - Finished processing 5 images.
2024-12-03 02:09:27.029 | INFO     | pcleaner.gui.mainwindow_driver:show_current_progress:2301 - Showing inpainter analytics...
2024-12-03 02:09:27.030 | INFO     | pcleaner.gui.processing:handle_merging_splits:965 - Merging split files...
2024-12-03 02:09:35.680 | INFO     | pcleaner.gui.mainwindow_driver:output_worker_result:2107 - Output worker finished.
2024-12-03 02:09:35.681 | INFO     | pcleaner.gui.output_review_driver:__init__:86 - Opening Review Window for 5 outputs.
2024-12-03 02:09:35.954 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for output_review
2024-12-03 02:09:53.003 | DEBUG    | pcleaner.gui.mainwindow_driver:output_review_closed:2161 - Output review closed.
2024-12-03 02:09:54.728 | INFO     | pcleaner.gui.mainwindow_driver:post_review_export:1900 - Starting post review export.
2024-12-03 02:09:54.730 | DEBUG    | pcleaner.gui.state_saver:save:65 - Saved state for output_review
2024-12-03 02:09:54.750 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1053 - Updating post action drawer: None
2024-12-03 02:09:54.751 | CRITICAL | pcleaner.gui.mainwindow_driver:output_worker_error:2215 - Encountered an error while processing files.
Traceback (most recent call last):

> File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {'progress_callback': <PySide6.QtCore.SignalInstance progress(PyObject) at 0x0000025397099110>, 'abort_flag': <pcleaner.gui.w...
             │    │   │    │       └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>
             │    │   │    └ ([<Output.inpainted_output: 21>, <Output.inpainted_mask: 20>, <Output.write_output: 22>], WindowsPath('D:/edit/kuro neko/The ...
             │    │   └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>
             │    └ <bound method MainWindow.generate_output of <pcleaner.gui.mainwindow_driver.MainWindow(0x253b7aaa1d0, name="MainWindow") at 0...
             └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\mainwindow_driver.py", line 1982, in generate_output
    prc.generate_output(
    │   └ <function generate_output at 0x00000253C6073EB0>
    └ <module 'pcleaner.gui.processing' from 'C:\\Users\\aaa13\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pc...

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\processing.py", line 174, in generate_output
    step_text_detector_images = tuple(

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\processing.py", line 150, in step_changed
    return image_object.outputs[representative].is_changed(profile)
           │                    │                          └ Profile(general=GeneralConfig(notes='', preferred_file_type=None, preferred_mask_file_type='.png', layered_export='psd-per-im...
           │                    └ <Output.raw_json: 4>
           └ <pcleaner.gui.image_file.MergedImageFile object at 0x000002542C667E80>

AttributeError: 'MergedImageFile' object has no attribute 'outputs'

**Comment by wolfkingal2000** [comment]
this error in terminal

2024-12-03 01:55:49.398 | ERROR    | pcleaner.ocr.ocr_tesseract:available_langs:32 - Error checking Tesseract available language data: tesseract is not installed or it's not in your PATH. See README file for more information.
2024-12-03 02:08:03.665 | WARNING  | pcleaner.gui.mainwindow_driver:profile_change_check:1411 - Profile change check
2024-12-03 02:09:54.751 | CRITICAL | pcleaner.gui.mainwindow_driver:output_worker_error:2215 - Encountered an error while processing files.
Traceback (most recent call last):

> File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {'progress_callback': <PySide6.QtCore.SignalInstance progress(PyObject) at 0x0000025397099110>, 'abort_flag': <pcleaner.gui.w...
             │    │   │    │       └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>
             │    │   │    └ ([<Output.inpainted_output: 21>, <Output.inpainted_mask: 20>, <Output.write_output: 22>], WindowsPath('D:/edit/kuro neko/The ...
             │    │   └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>
             │    └ <bound method MainWindow.generate_output of <pcleaner.gui.mainwindow_driver.MainWindow(0x253b7aaa1d0, name="MainWindow") at 0...
             └ <pcleaner.gui.worker_thread.Worker object at 0x000002542D228E80>

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\mainwindow_driver.py", line 1982, in generate_output
    prc.generate_output(
    │   └ <function generate_output at 0x00000253C6073EB0>
    └ <module 'pcleaner.gui.processing' from 'C:\\Users\\aaa13\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pc...

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\processing.py", line 174, in generate_output
    step_text_detector_images = tuple(

  File "C:\Users\aaa13\AppData\Local\Programs\Python\Python310\lib\site-packages\pcleaner\gui\processing.py", line 150, in step_changed
    return image_object.outputs[representative].is_changed(profile)
           │                    │                          └ Profile(general=GeneralConfig(notes='', preferred_file_type=None, preferred_mask_file_type='.png', layered_export='psd-per-im...
           │                    └ <Output.raw_json: 4>
           └ <pcleaner.gui.image_file.MergedImageFile object at 0x000002542C667E80>

AttributeError: 'MergedImageFile' object has no attribute 'outputs'

**Comment by VoxelCubes** [comment]
Oooh, now that's weird. It's an error in my code, so I can fix this. Could you please describe a short set of steps that cause the crash? 
From the log, you did quite a lot before it crashed, but it definitely has to do with merged split images, that much is sure.
Thanks for finding this!

**Comment by VoxelCubes** [comment]
Aha, the sneaky bug crept in due to a small change related to the Custom Post-Actions, which resulted in the image objects list being contaminated when processing but not exporting. This list is shared between processing and review, so if you review, which runs processing without exporting, then runs processing with exporting a second time, this contaminated list made it's way into the processing machinery, gunking it up.

I'll be fixed with 2.11.1
