### ISSUE TITLE
Failed to load OCR model

### ISSUE THREAD

**Issue by Owais5514** [VoxelCubes/PanelCleaner#141]
**Describe the bug**
DLL load failed while importing fugashi: The specified module could not be found.

**To Reproduce**
1. From command prompt type "pcleaner gui"
2. Takes a while to load and shows me the error

**Session Log**
2024-12-14 11:28:09.932 | INFO     | pcleaner.cli_utils:dump_system_info:292 - 
- Program Information -
Program: Panel Cleaner 2.11.4-1
Executing from: C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\launcher.py
Log file: C:\Users\<username>\AppData\Roaming\pcleaner\cache\pcleaner.log
Config file: C:\Users\<username>\AppData\Roaming\pcleaner\pcleanerconfig.ini
Cache directory: C:\Users\<username>\AppData\Roaming\pcleaner\cache
- System Information -
Operating System: Windows 11
Python Version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
PySide (Qt) Version: 6.8.1
Available Qt Themes: windows11, windowsvista, Windows, Fusion
Current Qt Theme: System Default
Current Icon Theme: System Default
System locale: en_US
Architecture: AMD64
CPU Cores: 8
Memory: 7.89 GiB
Swap: 3.38 GiB
GPU: NVIDIA GeForce MX130 (CUDA enabled)
    CUDA Version: 12.6
    CUDA Cores: 3
    VRAM: 2.00 GiB

2024-12-14 11:28:09.932 | INFO     | pcleaner.cli_utils:dump_system_info:292 - 
- Program Information -
Program: Panel Cleaner 2.11.4-1
Executing from: C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\launcher.py
Log file: C:\Users\<username>\AppData\Roaming\pcleaner\cache\pcleaner.log
Config file: C:\Users\<username>\AppData\Roaming\pcleaner\pcleanerconfig.ini
Cache directory: C:\Users\<username>\AppData\Roaming\pcleaner\cache
- System Information -
Operating System: Windows 11
Python Version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
PySide (Qt) Version: 6.8.1
Available Qt Themes: windows11, windowsvista, Windows, Fusion
Current Qt Theme: System Default
Current Icon Theme: System Default
System locale: en_US
Architecture: AMD64
CPU Cores: 8
Memory: 7.89 GiB
Swap: 3.38 GiB
GPU: NVIDIA GeForce MX130 (CUDA enabled)
    CUDA Version: 12.6
    CUDA Cores: 3
    VRAM: 2.00 GiB

2024-12-14 11:28:11.103 | INFO     | pcleaner.gui.launcher:launch:70 - Using locale en_US.
2024-12-14 11:28:11.103 | INFO     | pcleaner.gui.launcher:launch:70 - Using locale en_US.
2024-12-14 11:28:11.119 | DEBUG    | pcleaner.gui.launcher:launch:77 - Loaded built-in Qt translations for en_US.
2024-12-14 11:28:11.119 | DEBUG    | pcleaner.gui.launcher:launch:77 - Loaded built-in Qt translations for en_US.
2024-12-14 11:28:11.119 | DEBUG    | pcleaner.gui.launcher:launch:85 - Loaded built-in Qt base translations for en_US.
2024-12-14 11:28:11.119 | DEBUG    | pcleaner.gui.launcher:launch:85 - Loaded built-in Qt base translations for en_US.
2024-12-14 11:28:13.284 | DEBUG    | pcleaner.gui.mainwindow_driver:ensure_models_downloaded:478 - Text detector model already downloaded.
2024-12-14 11:28:13.284 | DEBUG    | pcleaner.gui.mainwindow_driver:ensure_models_downloaded:478 - Text detector model already downloaded.
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_ui:288 - Purging missing profiles.
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_ui:288 - Purging missing profiles.
2024-12-14 11:28:13.326 | INFO     | pcleaner.gui.mainwindow_driver:initialize_profiles:1238 - Found profiles: [('Default', None)]
2024-12-14 11:28:13.326 | INFO     | pcleaner.gui.mainwindow_driver:initialize_profiles:1238 - Found profiles: [('Default', None)]
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.config:load_profile:1361 - Loading profile None...
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.config:load_profile:1361 - Loading profile None...
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.config:load_profile:1368 - Loading builtin default profile
2024-12-14 11:28:13.326 | DEBUG    | pcleaner.config:load_profile:1368 - Loading builtin default profile
2024-12-14 11:28:13.386 | DEBUG    | pcleaner.gui.mainwindow_driver:load_current_profile:1398 - Loading current profile.
2024-12-14 11:28:13.386 | DEBUG    | pcleaner.gui.mainwindow_driver:load_current_profile:1398 - Loading current profile.
2024-12-14 11:28:13.386 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:565 - Setting profile values
2024-12-14 11:28:13.386 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:565 - Setting profile values
2024-12-14 11:28:13.402 | DEBUG    | pcleaner.gui.mainwindow_driver:apply_profile:1532 - Applying profile.
2024-12-14 11:28:13.402 | DEBUG    | pcleaner.gui.mainwindow_driver:apply_profile:1532 - Applying profile.
2024-12-14 11:28:13.402 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:565 - Setting profile values
2024-12-14 11:28:13.402 | DEBUG    | pcleaner.gui.profile_parser:set_profile_values:565 - Setting profile values
2024-12-14 11:28:13.788 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:823 - Loading included font from C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\data\NotoMono-Regular.ttf
2024-12-14 11:28:13.788 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:823 - Loading included font from C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\data\NotoMono-Regular.ttf
2024-12-14 11:28:13.798 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:826 - Loaded included font
2024-12-14 11:28:13.798 | DEBUG    | pcleaner.gui.mainwindow_driver:initialize_analytics_view:826 - Loaded included font
2024-12-14 11:28:13.814 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:13.814 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:13.830 | DEBUG    | pcleaner.gui.mainwindow_driver:save_default_palette:177 - Placeholder color: #000000
2024-12-14 11:28:13.830 | DEBUG    | pcleaner.gui.mainwindow_driver:save_default_palette:177 - Placeholder color: #000000
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:181 - Default Qt Style: windows11
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:181 - Default Qt Style: windows11
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:182 - Default Icon Theme: breeze
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:save_default_palette:182 - Default Icon Theme: breeze
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:198 - Using system theme.
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:198 - Using system theme.
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:changeEvent:269 - Theme is dark: False
2024-12-14 11:28:13.830 | INFO     | pcleaner.gui.mainwindow_driver:changeEvent:269 - Theme is dark: False
2024-12-14 11:28:13.846 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:13.846 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:13.846 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:246 - Theme is dark: False
2024-12-14 11:28:13.846 | INFO     | pcleaner.gui.mainwindow_driver:set_theme:246 - Theme is dark: False
2024-12-14 11:28:13.846 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:13.846 | DEBUG    | pcleaner.gui.mainwindow_driver:update_post_action_drawer:1051 - Updating post action drawer: None
2024-12-14 11:28:14.712 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:551 - Char width: 6, columns: 74, required width: 444
2024-12-14 11:28:14.712 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:551 - Char width: 6, columns: 74, required width: 444
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:582 - Splitter sizes: [375, 694, 458]
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:post_init:582 - Splitter sizes: [375, 694, 458]
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for Mainwindow
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.state_saver:restore:106 - Restored state for Mainwindow
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:711 - Worker Thread cleaning cache
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:711 - Worker Thread cleaning cache
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:718 - Worker Thread loading OCR model.
2024-12-14 11:28:14.726 | DEBUG    | pcleaner.gui.mainwindow_driver:start_initialization_worker:718 - Worker Thread loading OCR model.
2024-12-14 11:28:14.726 | INFO     | pcleaner.gui.mainwindow_driver:clean_cache:808 - Cleaning image cache.
2024-12-14 11:28:14.726 | INFO     | pcleaner.gui.mainwindow_driver:clean_cache:808 - Cleaning image cache.
2024-12-14 11:28:14.726 | INFO     | pcleaner.ocr.ocr_mangaocr:__new__:17 - Creating the MangaOcr instance
2024-12-14 11:28:14.726 | INFO     | pcleaner.ocr.ocr_mangaocr:__new__:17 - Creating the MangaOcr instance
2024-12-14 11:28:14.726 | INFO     | manga_ocr.ocr:__init__:16 - Loading OCR model from kha-white/manga-ocr-base
2024-12-14 11:28:14.726 | INFO     | manga_ocr.ocr:__init__:16 - Loading OCR model from kha-white/manga-ocr-base
2024-12-14 11:28:15.574 | CRITICAL | pcleaner.gui.mainwindow_driver:generic_worker_error:746 - Failed to load OCR model. OCR impossible, moderate cleaning impact.

Encountered error:
Traceback (most recent call last):

> File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
             │    │   │    └ ()
             │    │   └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
             │    └ <bound method MainWindow.load_ocr_model of <pcleaner.gui.mainwindow_driver.MainWindow(0x21b31d989e0, name="MainWindow") at 0x...
             └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\mainwindow_driver.py", line 733, in load_ocr_model
    ocr.ocr_engines()[cfg.OCREngine.MANGAOCR].initialize_model()
    │   │             │   │         └ <OCREngine.MANGAOCR: 'manga-ocr'>
    │   │             │   └ <enum 'OCREngine'>
    │   │             └ <module 'pcleaner.config' from 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra...
    │   └ <function ocr_engines at 0x0000021B4FFE5120>
    └ <module 'pcleaner.ocr.ocr' from 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfr...
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\ocr\ocr_mangaocr.py", line 37, in initialize_model
    self._model = MangaOcrModel(*init_args[0], **init_args[1])
    │    │        │              │               └ ((), {})
    │    │        │              └ ((), {})
    │    │        └ <class 'manga_ocr.ocr.MangaOcr'>
    │    └ None
    └ <pcleaner.ocr.ocr_mangaocr.MangaOcr object at 0x0000021B51A05E80>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\manga_ocr\ocr.py", line 18, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
    │                │             │               └ 'kha-white/manga-ocr-base'
    │                │             └ <classmethod(<function AutoTokenizer.from_pretrained at 0x0000021B3D024AE0>)>
    │                └ <class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
    └ <manga_ocr.ocr.MangaOcr object at 0x0000021B51A07890>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\auto\tokenization_auto.py", line 921, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           │               │               │                               │         └ {'_from_auto': True, '_commit_hash': 'aa6573bd10b0d446cbf622e29c3e084914df9741'}
           │               │               │                               └ ()
           │               │               └ 'kha-white/manga-ocr-base'
           │               └ <classmethod(<function PreTrainedTokenizerBase.from_pretrained at 0x0000021B3591CE00>)>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\tokenization_utils_base.py", line 2032, in from_pretrained
    return cls._from_pretrained(
           │   └ <classmethod(<function PreTrainedTokenizerBase._from_pretrained at 0x0000021B3591CEA0>)>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\tokenization_utils_base.py", line 2272, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                │    │              └ {'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]', 'do_lower_ca...
                │    └ ()
                └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 143, in __init__
    self.word_tokenizer = MecabTokenizer(
    │                     └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.MecabTokenizer'>
    └ <unprintable BertJapaneseTokenizer object>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 408, in __init__
    import fugashi
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *

ImportError: DLL load failed while importing fugashi: The specified module could not be found.
2024-12-14 11:28:15.574 | CRITICAL | pcleaner.gui.mainwindow_driver:generic_worker_error:746 - Failed to load OCR model. OCR impossible, moderate cleaning impact.

Encountered error:
Traceback (most recent call last):

> File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             │    │   │    │       │    └ {}
             │    │   │    │       └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
             │    │   │    └ ()
             │    │   └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
             │    └ <bound method MainWindow.load_ocr_model of <pcleaner.gui.mainwindow_driver.MainWindow(0x21b31d989e0, name="MainWindow") at 0x...
             └ <pcleaner.gui.worker_thread.Worker object at 0x0000021B6A0252C0>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\gui\mainwindow_driver.py", line 733, in load_ocr_model
    ocr.ocr_engines()[cfg.OCREngine.MANGAOCR].initialize_model()
    │   │             │   │         └ <OCREngine.MANGAOCR: 'manga-ocr'>
    │   │             │   └ <enum 'OCREngine'>
    │   │             └ <module 'pcleaner.config' from 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra...
    │   └ <function ocr_engines at 0x0000021B4FFE5120>
    └ <module 'pcleaner.ocr.ocr' from 'C:\\Users\\<username>\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfr...
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\pcleaner\ocr\ocr_mangaocr.py", line 37, in initialize_model
    self._model = MangaOcrModel(*init_args[0], **init_args[1])
    │    │        │              │               └ ((), {})
    │    │        │              └ ((), {})
    │    │        └ <class 'manga_ocr.ocr.MangaOcr'>
    │    └ None
    └ <pcleaner.ocr.ocr_mangaocr.MangaOcr object at 0x0000021B51A05E80>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\manga_ocr\ocr.py", line 18, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(pretrained_model_name_or_path)
    │                │             │               └ 'kha-white/manga-ocr-base'
    │                │             └ <classmethod(<function AutoTokenizer.from_pretrained at 0x0000021B3D024AE0>)>
    │                └ <class 'transformers.models.auto.tokenization_auto.AutoTokenizer'>
    └ <manga_ocr.ocr.MangaOcr object at 0x0000021B51A07890>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\auto\tokenization_auto.py", line 921, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           │               │               │                               │         └ {'_from_auto': True, '_commit_hash': 'aa6573bd10b0d446cbf622e29c3e084914df9741'}
           │               │               │                               └ ()
           │               │               └ 'kha-white/manga-ocr-base'
           │               └ <classmethod(<function PreTrainedTokenizerBase.from_pretrained at 0x0000021B3591CE00>)>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\tokenization_utils_base.py", line 2032, in from_pretrained
    return cls._from_pretrained(
           │   └ <classmethod(<function PreTrainedTokenizerBase._from_pretrained at 0x0000021B3591CEA0>)>
           └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\tokenization_utils_base.py", line 2272, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                │    │              └ {'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]', 'do_lower_ca...
                │    └ ()
                └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.BertJapaneseTokenizer'>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 143, in __init__
    self.word_tokenizer = MecabTokenizer(
    │                     └ <class 'transformers.models.bert_japanese.tokenization_bert_japanese.MecabTokenizer'>
    └ <unprintable BertJapaneseTokenizer object>
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\models\bert_japanese\tokenization_bert_japanese.py", line 408, in __init__
    import fugashi
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\fugashi\__init__.py", line 1, in <module>
    from .fugashi import *

ImportError: DLL load failed while importing fugashi: The specified module could not be found.

**Additional context**
I followed the instructions to setup CUDA. I even restarted my pc before running pcleaner.

**Comment by Owais5514** [comment]
I found the solution. It was related to installing python 3.12 using Windows store. After I installed it from the official python site, it worked

**Comment by VoxelCubes** [comment]
Cool and good.
