### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by Pappmann** [VoxelCubes/PanelCleaner#68]
have the following error installing pcleaner on fedora 39

>Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
   × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2mwq_b_4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-2mwq_b_4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-2mwq_b_4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-2mwq_b_4/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 15, in <module>
        File "/tmp/pip-install-dz2ghw9u/fugashi_7cbb0607515249439cc2f16d9ebb1123/fugashi_util.py", line 58, in check_libmecab
          raise RuntimeError("Could not configure working env. Have you installed MeCab?")
      RuntimeError: Could not configure working env. Have you installed MeCab?
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
note: This error originates from a subprocess, and is likely not a problem with pip.<

i installed `mecab` and have following error:
`param.cpp(69) [ifs] no such file or directory: /usr/lib64/mecab/dic/ipadic/dicrc`

**Comment by Pappmann** [comment]
pip install is too heavy, i installes flatpak version, but auto dark does not work there too.

**Comment by VoxelCubes** [comment]
What is autodark? You need to go to the menubar->settings->theme->dark

It works for sure with the flatpak.

**Comment by VoxelCubes** [comment]
The pip install will also download any cuda libraries available to you, hence it being several GB larger, but also having cuda support as a result.

As for the error, unfortunately I have no idea, sorry. Pip failing is beyond what I can address, that's a problem for your distro maintainers.
