### ISSUE TITLE
Error Traceback (most recent call last)

### ISSUE THREAD

**Issue by nyarino015** [VoxelCubes/PanelCleaner#9]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Scripts\pcleaner.exe\__main__.py", line 4, in <module>
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\pcleaner\main.py", line 124, in <module>
    import pcleaner.masker as cl
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\pcleaner\masker.py", line 6, in <module>
    import pcleaner.image_ops as ops
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\pcleaner\image_ops.py", line 11, in <module>
    import pcleaner.structures as st
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\pcleaner\structures.py", line 9, in <module>
    import magic
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\ANIX\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by VoxelCubes** [comment]
Windows isn't officially supported, but it should be possible for it to work on it.
In this case, you can try `pip uninstall python-magic` and then `pip install python-magic-bin`
If that doesn't work, then you should try running this through WSL. I don't use Windows, so I can't help you with that either, unfortunately.

Once I finish the GUI in a month or two, I will try to offer a dedicated windows .exe for such cases.

**Comment by FlukRocker** [comment]
hi after i delete python-magic now i got this new error

Encountered an error while processing files.

<class 'AttributeError'>: Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\pcleaner\gui\worker_thread.py", line 141, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pcleaner\gui\mainwindow_driver.py", line 1064, in generate_output
    prc.generate_output(
  File "C:\Python311\Lib\site-packages\pcleaner\gui\processing.py", line 228, in generate_output
    ocr_analytic = pp.prep_json_file(
                   ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pcleaner\preprocessor.py", line 114, in prep_json_file
    page_data.grow_boxes(preprocessor_conf.box_padding_initial, st.BoxType.BOX)
  File "C:\Python311\Lib\site-packages\pcleaner\structures.py", line 205, in grow_boxes
    boxes[i] = box.pad(padding, self.image_size)
                                ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pcleaner\structures.py", line 177, in image_size
    metadata = magic.from_file(self.image_path)
               ^^^^^^^^^^^^^^^
AttributeError: module 'magic' has no attribute 'from_file'

module 'magic' has no attribute 'from_file'

**Comment by VoxelCubes** [comment]
You forgot to install python-magic-bin afterwards as the replacement. I'd only recommend installing with pip if you already know how to use python, as conflicts may arise with whatever is already in your python environment. Use the pre-built executable in the releases section https://github.com/VoxelCubes/PanelCleaner/releases
or proceed at your own risk with pip.

**Comment by FlukRocker** [comment]
i'm already rollback to use prebuild. it might slower but it work fine.
